on:
  push:
    branches: [main]
name: Flatpak Build
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-47
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: nyarchupdater.flatpak
          manifest-path: moe.nyarchlinux.updater.json
          cache-key: flatpak-builder-${{ github.sha }}